In [2]:
#imports
import numpy as np
import pandas as pd
from scipy.stats import zscore
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
import seaborn as sns
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from scipy.stats import zscore
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
from sklearn import metrics

In [9]:
data=pd.read_excel("New Microsoft Excel Worksheet.xlsx")
data.head()

x1    x2
0  4.79 -8.65
1  1.22 -2.42
2  1.43 -2.03
3  2.71 -4.96
4  4.30 -7.96

In [16]:
cova=np.cov(data.x1,data.x2)

In [43]:
cova1=np.matrix([[1.36,-2.35], [-2.35,4.18]])

In [32]:
sd=np.matrix([[1], [1]])
sd

matrix([[1],
        [1]])

In [25]:
cova*sd

matrix([[-0.73154667],
        [ 3.36296667]])

In [30]:
sd1=np.matrix([[-0.49], [0.87]])

In [31]:
cova1*sd1

matrix([[-2.7109],
        [ 4.7881]])

In [35]:
from numpy import linalg as LA

In [40]:
a=LA.eig(cova1)
print(a)

(array([0.02945261, 5.51054739]), matrix([[-0.87019991,  0.49269881],
        [-0.49269881, -0.87019991]]))
