In [59]:
#imports
import numpy as np
import pandas as pd
from scipy.stats import zscore
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
import seaborn as sns
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from scipy.stats import zscore
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [46]:
df=pd.read_csv("wine.csv",header = None )
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [7]:
data.shape


(178, 14)

In [8]:
data.dtypes
#every features is in int type.?

0       int64
1     float64
2     float64
3     float64
4     float64
5       int64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13      int64
dtype: object

In [144]:
data.describe().T

count        mean         std     min       25%      50%       75%  \
0   178.0    1.938202    0.775035    1.00    1.0000    2.000    3.0000   
1   178.0   13.000618    0.811827   11.03   12.3625   13.050   13.6775   
2   178.0    2.336348    1.117146    0.74    1.6025    1.865    3.0825   
3   178.0    2.366517    0.274344    1.36    2.2100    2.360    2.5575   
4   178.0   19.494944    3.339564   10.60   17.2000   19.500   21.5000   
5   178.0   99.741573   14.282484   70.00   88.0000   98.000  107.0000   
6   178.0    2.295112    0.625851    0.98    1.7425    2.355    2.8000   
7   178.0    2.029270    0.998859    0.34    1.2050    2.135    2.8750   
8   178.0    0.361854    0.124453    0.13    0.2700    0.340    0.4375   
9   178.0    1.590899    0.572359    0.41    1.2500    1.555    1.9500   
10  178.0    5.058090    2.318286    1.28    3.2200    4.690    6.2000   
11  178.0    0.957449    0.228572    0.48    0.7825    0.965    1.1200   
12  178.0    2.611685    0.709990    1.27    1.9375    2.780    3.1700   
13  178.0  746.893258  314.907474  278.00  500.5000  673.500  985.0000   

        max  
0      3.00  
1     14.83  
2      5.80  
3      3.23  
4     30.00  
5    162.00  
6      3.88  
7      5.08  
8      0.66  
9      3.58  
10    13.00  
11     1.71  
12     4.00  
13  1680.00

In [47]:
#Applying Z-score for table df1
z_data= df.apply(zscore)
z_data.head()

0         1         2         3         4         5         6   \
0 -1.213944  1.518613 -0.562250  0.232053 -1.169593  1.913905  0.808997   
1 -1.213944  0.246290 -0.499413 -0.827996 -2.490847  0.018145  0.568648   
2 -1.213944  0.196879  0.021231  1.109334 -0.268738  0.088358  0.808997   
3 -1.213944  1.691550 -0.346811  0.487926 -0.809251  0.930918  2.491446   
4 -1.213944  0.295700  0.227694  1.840403  0.451946  1.281985  0.808997   

         7         8         9         10        11        12        13  
0  1.034819 -0.659563  1.224884  0.251717  0.362177  1.847920  1.013009  
1  0.733629 -0.820719 -0.544721 -0.293321  0.406051  1.113449  0.965242  
2  1.215533 -0.498407  2.135968  0.269020  0.318304  0.788587  1.395148  
3  1.466525 -0.981875  1.032155  1.186068 -0.427544  1.184071  2.334574  
4  0.663351  0.226796  0.401404 -0.319276  0.362177  0.449601 -0.037874

In [113]:
import numpy as np
from sklearn.decomposition import PCA
pca = PCA(n_components=14, svd_solver='full')

In [123]:
pca.fit(z_data)
print(pca.explained_variance_ratio_) 

[0.39542486 0.17836259 0.10329102 0.06627984 0.06267875 0.0480556
 0.03955707 0.02500244 0.02103871 0.01873615 0.01613203 0.01205691
 0.00925458]


In [50]:
print(pca.singular_values_)

[31.39106164 21.08268417 16.04372811 12.85182374 12.49781774 10.94324196
  9.92855551  7.89342019  7.24075035  6.83304366  6.34042735  5.48140633
  4.80233525]


In [154]:
features = [1,2,3,4,5,6,7,8,9,10,11,12,13]

x = df.loc[:, features].values
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(x)
X


array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [110]:
from sklearn.preprocessing import StandardScaler

In [155]:
from sklearn.decomposition import PCA
pca = PCA(n_components=13)
principalComponents = pca.fit_transform(X) 

In [156]:
pca.explained_variance_

array([4.73243698, 2.51108093, 1.45424187, 0.92416587, 0.85804868,
       0.64528221, 0.55414147, 0.35046627, 0.29051203, 0.25232001,
       0.22706428, 0.16972374, 0.10396199])

In [157]:
print(pca.explained_variance_ratio_)

[0.36198848 0.1920749  0.11123631 0.0706903  0.06563294 0.04935823
 0.04238679 0.02680749 0.02222153 0.01930019 0.01736836 0.01298233
 0.00795215]


In [158]:
pca.explained_variance_ratio_.cumsum()

array([0.36198848, 0.55406338, 0.66529969, 0.73598999, 0.80162293,
       0.85098116, 0.89336795, 0.92017544, 0.94239698, 0.96169717,
       0.97906553, 0.99204785, 1.        ])

In [131]:
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['x1','x2','x3','x4','x5','x6','x7','x8','x9','x10','x11','x12','x13'])

finalDf = pd.concat([principalDf, df[[0]]], axis = 1)

features= finalDf[['x1','x2','x3','x4','x5','x6']]


label = np.array(finalDf[0])


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=0)

DTClassifier= DecisionTreeClassifier (max_depth=20, min_samples_split =5,criterion='gini',min_samples_leaf=2)
DTClassifier.fit(X_train,y_train)
predicted_labels = DTClassifier.predict(X_train)
predicted_labels

accuracy_scoree = accuracy_score(y_train,predicted_labels)
print(accuracy_scoree)

0.971830985915493


In [135]:
DTClassifier= DecisionTreeClassifier (max_depth=20, min_samples_split =5,criterion='gini',min_samples_leaf=2)
DTClassifier.fit(features,label)
predicted_labels = DTClassifier.predict(features)
predicted_labels
accuracy_scoree = accuracy_score(label,predicted_labels)
print(accuracy_scoree)

0.9662921348314607


In [141]:
#without PCA
features = [1,2,3,4,5,6,7,8,9,10,11,12,13]
x = df.loc[:, features].values
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(x)


DTClassifier= DecisionTreeClassifier (max_depth=20, min_samples_split =5,criterion='gini',min_samples_leaf=2)
DTClassifier.fit(X,label)
predicted_labels = DTClassifier.predict(X)
predicted_labels
accuracy_scoree = accuracy_score(label,predicted_labels)
print(accuracy_scoree)

0.9887640449438202


In [142]:
#without PCA
features = [1,2,3,4,5,6,7,8,9,10,11,12,13]
x = df.loc[:, features].values
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(x)


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, label, test_size=0.2, random_state=0)

DTClassifier= DecisionTreeClassifier (max_depth=20, min_samples_split =5,criterion='gini',min_samples_leaf=2)
DTClassifier.fit(X_train,y_train)
predicted_labels = DTClassifier.predict(X_train)
predicted_labels

accuracy_scoree = accuracy_score(y_train,predicted_labels)
print(accuracy_scoree)

0.9929577464788732
